### Create User

POST http://localhost:3000/api/auth/register

{
    "fullname": "unique",
    "email": "hahi@gmail.com",
    "password" : "112233"
}

### Login User

POST http://localhost:3000/api/auth/login

{
    "email": "hahi@gmail.com",
    "password" : "112233"
}
